### ISSUE TITLE
Heavy processor usage on the jvascript side with big canvas.

### ISSUE THREAD

**Issue by gery** [ttulka/2d-videogame-in-assemblyscript#3]
I have a 3000x2000 pixel canvas, 
This js code runs on every animation frame:

```javascript

  const bytes = new Uint8ClampedArray(buffer);
  
  for (let i = 0; i < WIDTH * HEIGHT * 4; i++) 
     imageData.data[i] = bytes[i];

```
Is there any faster solution? with not creating a new Object, and not drawing every byte with javascript?

Maybe something like this example :
https://github.com/AssemblyScript/examples/tree/main/game-of-life

Thanks ;)

**Comment by ttulka** [comment]
Thanks for bringing this up, @gery !
Copying data in the loop is quite self-explanatory but not very efficient, indeed.

I have changed the JS glue to copy the memory using 32bit arrays ([starting with this line](https://github.com/ttulka/2d-videogame-in-assemblyscript/blob/5e0b15460af7c92c8952e415c190ba6c4ccec613/src/index.js#L51)).

Check it out and let me know if this helped solve your issue!

**Comment by gery** [comment]
It's much better. thanks.

**Comment by ttulka** [comment]
Nice.
